POST https://csm-backend-h2ht.onrender.com/api/users
Content-Type: application/json

{
  "username": "ismael",
  "email": "ismael@example.com",
  "password": "ismael123"
}

###

POST https://csm-backend-h2ht.onrender.com/api/reviews
Content-Type: application/json

{
  "userId": "688bed9d5a88d0a7360dc52b",
  "content": "Game was pretty mid, quite a few bugs but overall enjoyable.",
  "rating": 3
}

###

POST https://csm-backend-h2ht.onrender.com/api/patchlog
Content-Type: application/json

{
  "currentVersion": "1.0.0"
}

###

GET https://csm-backend-h2ht.onrender.com/api/reviews

###

PATCH https://csm-backend-h2ht.onrender.com/api/reviews/update
Content-Type: application/json

{
  "reviewId": "687195a9b23f40d4f0954482",
  "updates": {
    "likes": 1
  }
}

###

POST https://csm-backend-h2ht.onrender.com/api/release-note
Content-Type: application/json

{
  "version": [1, 0, 2],
  "text": "• Issue where people could not jump sometimes in game has been resolved.",
  "passKey": "yug0er98yi34j09frhuf08u3bdfdpoklqs"
}

###

GET https://csm-backend-h2ht.onrender.com/api/release-note/latest